# Generated by Django 5.2.15 on 2026-06-22 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_etb', models.CharField(db_index=True, max_length=20)),
                ('nom', models.CharField(max_length=255)),
                ('wilaya', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('is_national', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['code_etb', 'nom'], name='orientation_code_et_94e32a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_fil', models.CharField(db_index=True, max_length=20)),
                ('nom', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['code_fil'], name='orientation_code_fi_6c87df_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResultatAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(db_index=True)),
                ('min1', models.FloatField(blank=True, null=True)),
                ('min2', models.FloatField(blank=True, null=True)),
                ('min3', models.FloatField(blank=True, null=True)),
                ('source_pdf', models.CharField(blank=True, max_length=255)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='orientation.etablissement')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='orientation.filiere')),
            ],
            options={
                'indexes': [models.Index(fields=['annee'], name='orientation_annee_e5825a_idx')],
                'constraints': [models.UniqueConstraint(fields=('etablissement', 'filiere', 'annee'), name='unique_resultat_par_annee')],
            },
        ),
    ]
