# Generated by Django 5.2.15 on 2026-07-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacStreamPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine_code', models.CharField(db_index=True, max_length=5)),
                ('bac_stream', models.CharField(choices=[('SM', 'Sciences et Mathématiques (Riadhiyat)'), ('SE', 'Sciences Expérimentales (علوم تجريبية)'), ('TR', 'Technique et Raisonnement (Taqni Riadhi)'), ('GE', 'Gestion et Économie (Tasyir wa Iqtisad)'), ('LL', 'Langues et Littérature (Loghate)'), ('LAL', 'Lettres et Langue Arabe (Adab wa Falsafa)'), ('ART', 'Arts'), ('STAPS', 'Sport (جميع الشعب)')], max_length=10)),
                ('priority', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Priorité par filière de bac',
            },
        ),
        migrations.CreateModel(
            name='DomainFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine_code', models.CharField(db_index=True, max_length=5, unique=True)),
                ('domaine_label', models.CharField(max_length=255)),
                ('formula_type', models.CharField(choices=[('general', 'Moyenne générale uniquement'), ('snv', 'Bac×2 + SVT / 3'), ('sm', 'Bac×2 + (Physique+Maths)/2 / 3'), ('mi', 'Bac×2 + Maths / 3'), ('arch', 'Bac×2 + (Physique+Maths)/2 / 3'), ('lang', 'Bac×2 + Note langue demandée / 3'), ('trad', 'Bac×2 + Moy 3 langues / 3'), ('st_spec', 'Bac×2 + (Spécialité+Maths)/2 / 3')], max_length=20)),
                ('langue_cible', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Formule de domaine',
            },
        ),
        migrations.RemoveIndex(
            model_name='etablissement',
            name='orientation_code_et_94e32a_idx',
        ),
        migrations.RemoveIndex(
            model_name='filiere',
            name='orientation_code_fi_6c87df_idx',
        ),
        migrations.AddField(
            model_name='etablissement',
            name='type_etablissement',
            field=models.CharField(choices=[('universite', 'Université'), ('centre_universitaire', 'Centre Universitaire'), ('grande_ecole', 'Grande École / École Nationale Supérieure'), ('ens', 'École Normale Supérieure (Formation enseignants)'), ('institut_sante', 'Institut de Santé Publique (INFSSF…)'), ('formation_continue', 'Centre de Formation Continue'), ('national', 'Recrutement National')], default='universite', max_length=30),
        ),
        migrations.AddField(
            model_name='filiere',
            name='domaine_code',
            field=models.CharField(db_index=True, default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filiere',
            name='type_inscription',
            field=models.CharField(choices=[('local', 'Local / Régional'), ('national', 'National')], default='local', max_length=10),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='code_etb',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='filiere',
            unique_together={('code_fil', 'type_inscription')},
        ),
        migrations.AddIndex(
            model_name='etablissement',
            index=models.Index(fields=['wilaya', 'type_etablissement'], name='orientation_wilaya_417808_idx'),
        ),
        migrations.AddIndex(
            model_name='filiere',
            index=models.Index(fields=['domaine_code'], name='orientation_domaine_d68c62_idx'),
        ),
        migrations.AddIndex(
            model_name='filiere',
            index=models.Index(fields=['type_inscription'], name='orientation_type_in_6b72d8_idx'),
        ),
        migrations.AddIndex(
            model_name='resultatadmission',
            index=models.Index(fields=['etablissement', 'annee'], name='orientation_etablis_c604dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bacstreampriority',
            unique_together={('domaine_code', 'bac_stream')},
        ),
    ]
