# Generated by Django 5.2.15 on 2026-07-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0002_bacstreampriority_domainformula_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filiere',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='filiere',
            name='wilaya_cible',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='filiere',
            unique_together={('code_fil', 'wilaya_cible')},
        ),
    ]
